import { Header } from '@/components/Header';
import './globals.css';
import { Saira } from 'next/font/google';
import { FilterTypeContextProvider } from '@/context/FilterContext';
import { CartContextProvider } from '@/context/CartContext';

const saira = Saira({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'capputeeno',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={saira.className}>
        <CartContextProvider>
          <FilterTypeContextProvider>
            <Header />
            {children}
          </FilterTypeContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
