import { Header } from '@/components/Header';
import './globals.css';
import { Saira } from 'next/font/google';
import { FilterTypeContextProvider } from '@/context/FilterContext';

const saira = Saira({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterTypeContextProvider>
          <Header />
          {children}
        </FilterTypeContextProvider>
      </body>
    </html>
  );
}
